import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [promptValue, setPromptValue] = useState<string>('')

  async function handleSubmit() {
    console.log('nothing rn')
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col min-h-screen justify-items-center items-center'>

            <textarea className='my-10 w-[900px] min-h-[70vh] focus:border-none focus:ring-0 bg-gray-200 focus:outline-none outline-0' contentEditable={true} placeholder='Your prompt here' value={promptValue} onChange={(e) => setPromptValue(e.target.value)}/>
            <button onClick={handleSubmit} className='mt-1 bg-green-400 p-3 rounded-2xl'>Submit</button>
      </div>
      <table></table>
    </>
  )
}
